## Compiling the user-level swifi controller
## You may need to adjust your include path to include <linux/swifi-user.h>

CC := gcc
LD := gcc

PROG := swifi

all: $(PROG)

$(PROG): swifi.c

clean:
	rm -f $(PROG)
